import json
import csv

# This script finds the respective regional food names from the input file regionalFoodNamesOrderedByCode.csv 
# (generated by 2_group_food_regional_names_by_code.py) and appends the additional details in the given
# IndianFoodCompositionTable_In_JSON_Format.json file (generated by the script 3_convert_IFCT_csv_format_to_json.py)
# INPUT: regionalFoodNamesOrderedByCode.csv & IndianFoodCompositionTable_In_JSON_Format.json
# OUTPUT: IndianFoodCompositionTable_In_JSON_Format_With_Sorted_RegionalNames.json

lang_map = {
    'A.': 'Assamese',
    'B.': 'Bengali',
    'G.': 'Gujarati',
    'H.': 'Hindi',
    'Kan.': 'Kannada',
    'Kash.': 'Kashmiri',
    'Kh.': 'Khasi',
    'Kon.': 'Konkani',
    'Mal.': 'Malayalam',
    'M.': 'Manipuri',
    'Mar.': 'Marathi',
    'N.': 'Nepali',
    'O.': 'Oriya',
    'P.': 'Punjabi',
    'S.': 'Sanskrit',
    'Tam.': 'Tamil',
    'Tel.': 'Telugu',
    'U.': 'Urdu',
    'Sci.': 'Scientific Name',
    'Common.': 'Common Name'
}

# Load the JSON file
json_file = open('IndianFoodCompositionTable_In_JSON_Format.json', 'r')
data = json.load(json_file)
json_file.close()

# Iterate over the data and update regionalNames
for item in data:
    with open('regionalFoodNamesOrderedByCode.csv', 'r', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile, delimiter=',')
        for row in reader:
            code = row['code']
            names = row['names']
            #print("code = ", code)
            if code == item['code']:
                rnames = {}
                for langs in names.split('|'):
                    lang_parts = langs.split('(')
                    regional_food_name = lang_parts[0].strip()
                    lang_code = lang_parts[1].split(')')[0]
                    for lang in lang_code.split(','):
                        lang = lang.strip().capitalize()

                        # Append '.' if it's not already there
                        if not lang.endswith('.'):
                            lang += '.'
                        full_lang_name = lang_map.get(lang, 'Unknown')
                        rnames[full_lang_name] = regional_food_name
                        sorted_rnames = dict(sorted(rnames.items()))
                    item['regionalNames'] = sorted_rnames

# Save the updated data to a new JSON file
with open('IndianFoodCompositionTable_In_JSON_Format_With_Sorted_RegionalNames.json', 'w') as outfile:
    json.dump(data, outfile, indent=4)
